language: python
node_js:
- node
python:
- '3.7'
cache: pip
before_install:
- 'pip install pipenv'
- 'pipenv install'
script: 'python -m pytest --cov=pyblizzard tests --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'