language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
sudo: required
dist: xenial
python:
- '3.7'
cache: pip
before_install:
- 'pip install pipenv'
- 'pipenv install --dev'
script: 'make ci'
after_success:
  - 'pipenv run python-codacy-coverage -r coverage.xml'