language: python
sudo: required
dist: xenial
python:
- '3.7'
cache: pip
before_install:
- 'pip install pipenv'
- 'pipenv sync'
script: 'make ci'
# after_success:
#   - 'python-codacy-coverage -r coverage.xml'